language: php

php:
  - 5.6

before_script:
  - mkdir bootstrap/cache
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - chmod -R 755 storage
  - php artisan key:generate
script:
  - vendor/bin/phpunit